// constants/routeConstants.js
export const ROUTE_PATHS = {
  HOME: '/',
  

  SYSTEM_INFO: '/operation-info/system-info',
  PSTN_STATUS: '/operation-info/pstn-status',
  CALL_COUNT: '/operation-info/call-count',
  SIP_MESSAGE_COUNT: '/operation-info/sip-message-count',
  QUICK_CONFIG: '/quick-config',
  // Main routes
  VOIP: '/voip',
  SIP_COMPATIBILITY: '/voip/sip-compatibility',
  NAT_SETTINGS: '/voip/nat-settings',
  SIP_MEDIA: '/voip/media',
  PCM: '/pcm',
  ISDN: '/isdn',
  ADVANCED:'/advanced',
  FAX: '/fax',
  FXS: '/fxs',
  TONE_DETECTER: '/tone-detecter',
  TONE_GENERATOR: '/tone-generator',
  DTMF: '/dtmf',
  RINGING_SCHEME: '/ringing-scheme',
  FUNCTION_KEY: '/function-key',
  DIALING_RULE: '/dialing-rule',
  DIALING_TIMEOUT: '/dialing-timeout',
  CUE_TONE: '/cue-tone',
  COLOR_RING: '/color-ring',
  QOS: '/qos',
  ACTION_URL: '/action-url',
  CDR_QUERY: '/cdr-query',
  VPN_SETTINGS: '/vpn-settings',
  AREA_SELECT: '/area-select',
  USER_MANAGE: '/user-manage',
  PORT: '/port',
  PORT_FXS: '/port/fxs',
  PORT_FXS_ADVANCED: '/port/fxs-advanced',
  PORT_FXS_BATCH_MODIFY: '/port/fxs/batch-modify',
  PORT_GROUP: '/port/port-group',
  ROUTE: '/route',

  NUMBER_FILTER: '/number-filter',
  NUM_MANIPULATE: '/num-manipulate',
  VPN: '/vpn',
  DHCP: '/dhcp',
  SYSTEM_TOOLS: '/system-tools',
  IP_CALL_IN_CALLERID: '/num-manipulate/ip-call-in-callerid',
  IP_CALL_IN_CALLEEID: '/num-manipulate/ip-call-in-calleeid',
  IP_CALL_IN_ORICALLEEID: '/num-manipulate/ip-call-in-oricalleeid',
  PSTN_CALL_IN_CALLERID: '/num-manipulate/pstn-call-in-callerid',
  PSTN_CALL_IN_CALLEEID: '/num-manipulate/pstn-call-in-calleeid',
  PSTN_CALL_IN_ORICALLEEID: '/num-manipulate/pstn-call-in-oricalleeid',
  CALLERID_POOL: '/num-manipulate/callerid-pool',
  CALLERID_RESERVE_POOL: '/num-manipulate/callerid-reserve-pool',
};


